// This file would normally be auto-generated by running:
//   flutter pub run build_runner build
// Since you're building from a phone with no way to run that command,
// this is hand-written to match exactly what the generator would output.
// If you ever DO run build_runner locally, it's safe to let it
// overwrite this file.
part of 'user_profile.dart';

class UserProfileAdapter extends TypeAdapter<UserProfile> {
  @override
  final int typeId = 3; // must match @HiveType(typeId: 3) above

  // Reads bytes from disk and reconstructs a UserProfile object
  @override
  UserProfile read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return UserProfile(
      name: fields[0] as String,
      age: fields[1] as int,
      gender: fields[2] as String,
      heightCm: fields[3] as double,
      weightKg: fields[4] as double,
      fitnessLevel: fields[5] as FitnessLevel,
      primaryGoal: fields[6] as PrimaryGoal,
      preferredWorkoutDays: (fields[7] as List).cast<int>(),
      workoutLocation: fields[8] as WorkoutLocation,
      availableEquipment: (fields[9] as List).cast<String>(),
      dailyReminderHour: fields[10] as int,
      dailyReminderMinute: fields[11] as int,
      isGuest: fields[12] as bool,
      level: fields[13] as int,
      xp: fields[14] as int,
      currentStreak: fields[15] as int,
      longestStreak: fields[16] as int,
    );
  }

  // Writes a UserProfile object out to bytes on disk
  @override
  void write(BinaryWriter writer, UserProfile obj) {
    writer
      ..writeByte(17) // number of fields being written
      ..writeByte(0)
      ..write(obj.name)
      ..writeByte(1)
      ..write(obj.age)
      ..writeByte(2)
      ..write(obj.gender)
      ..writeByte(3)
      ..write(obj.heightCm)
      ..writeByte(4)
      ..write(obj.weightKg)
      ..writeByte(5)
      ..write(obj.fitnessLevel)
      ..writeByte(6)
      ..write(obj.primaryGoal)
      ..writeByte(7)
      ..write(obj.preferredWorkoutDays)
      ..writeByte(8)
      ..write(obj.workoutLocation)
      ..writeByte(9)
      ..write(obj.availableEquipment)
      ..writeByte(10)
      ..write(obj.dailyReminderHour)
      ..writeByte(11)
      ..write(obj.dailyReminderMinute)
      ..writeByte(12)
      ..write(obj.isGuest)
      ..writeByte(13)
      ..write(obj.level)
      ..writeByte(14)
      ..write(obj.xp)
      ..writeByte(15)
      ..write(obj.currentStreak)
      ..writeByte(16)
      ..write(obj.longestStreak);
  }
}

class FitnessLevelAdapter extends TypeAdapter<FitnessLevel> {
  @override
  final int typeId = 0;

  @override
  FitnessLevel read(BinaryReader reader) => FitnessLevel.values[reader.readByte()];

  @override
  void write(BinaryWriter writer, FitnessLevel obj) => writer.writeByte(obj.index);
}

class PrimaryGoalAdapter extends TypeAdapter<PrimaryGoal> {
  @override
  final int typeId = 1;

  @override
  PrimaryGoal read(BinaryReader reader) => PrimaryGoal.values[reader.readByte()];

  @override
  void write(BinaryWriter writer, PrimaryGoal obj) => writer.writeByte(obj.index);
}

class WorkoutLocationAdapter extends TypeAdapter<WorkoutLocation> {
  @override
  final int typeId = 2;

  @override
  WorkoutLocation read(BinaryReader reader) => WorkoutLocation.values[reader.readByte()];

  @override
  void write(BinaryWriter writer, WorkoutLocation obj) => writer.writeByte(obj.index);
}
