import 'package:hive/hive.dart';

// This links to the hand-written adapter file below (normally this
// file would be auto-generated by running build_runner, but since we
// can't run that from a phone, it's written by hand and kept in sync).
part 'user_profile.g.dart';

// @HiveType marks this enum as something Hive can save to disk.
// typeId must be unique across ALL Hive types in the whole app.
@HiveType(typeId: 0)
enum FitnessLevel {
  @HiveField(0)
  beginner,
  @HiveField(1)
  intermediate,
  @HiveField(2)
  advanced,
}

@HiveType(typeId: 1)
enum PrimaryGoal {
  @HiveField(0)
  loseWeight,
  @HiveField(1)
  gainMuscle,
  @HiveField(2)
  buildDiscipline,
  @HiveField(3)
  improveHealth,
  @HiveField(4)
  increaseStrength,
  @HiveField(5)
  improveEndurance,
}

@HiveType(typeId: 2)
enum WorkoutLocation {
  @HiveField(0)
  home,
  @HiveField(1)
  gym,
}

// This is the main object saved to local storage after onboarding.
// HiveObject gives it a .save() method for free.
@HiveType(typeId: 3)
class UserProfile extends HiveObject {
  UserProfile({
    required this.name,
    required this.age,
    required this.gender,
    required this.heightCm,
    required this.weightKg,
    required this.fitnessLevel,
    required this.primaryGoal,
    required this.preferredWorkoutDays,
    required this.workoutLocation,
    required this.availableEquipment,
    required this.dailyReminderHour,
    required this.dailyReminderMinute,
    this.isGuest = false,
    this.level = 1,
    this.xp = 0,
    this.currentStreak = 0,
    this.longestStreak = 0,
  });

  @HiveField(0)
  String name;

  @HiveField(1)
  int age;

  @HiveField(2)
  String gender;

  @HiveField(3)
  double heightCm;

  @HiveField(4)
  double weightKg;

  @HiveField(5)
  FitnessLevel fitnessLevel;

  @HiveField(6)
  PrimaryGoal primaryGoal;

  // Weekday numbers: 1 = Monday ... 7 = Sunday
  @HiveField(7)
  List<int> preferredWorkoutDays;

  @HiveField(8)
  WorkoutLocation workoutLocation;

  @HiveField(9)
  List<String> availableEquipment;

  @HiveField(10)
  int dailyReminderHour;

  @HiveField(11)
  int dailyReminderMinute;

  @HiveField(12)
  bool isGuest;

  @HiveField(13)
  int level;

  @HiveField(14)
  int xp;

  @HiveField(15)
  int currentStreak;

  @HiveField(16)
  int longestStreak;

  /// How much XP is needed to reach the next level.
  /// This is a simple increasing curve — feel free to tune the numbers
  /// later once you've playtested how fast leveling feels.
  int get xpToNextLevel => 100 + (level - 1) * 50;

  /// Current progress toward the next level, as a 0.0–1.0 fraction,
  /// used directly by ProgressRing widgets.
  double get levelProgress => (xp / xpToNextLevel).clamp(0, 1).toDouble();
}
